package desktop

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

/*
Script writes the KWin script that binds the keys.

Generated rather than shipped as a file, because the bindings are the user's
and the script is only their spelling. It does two things per key: register the
shortcut, and call hotaru's door when it fires.

`print` lines are not debugging left in by accident. A key that never fired and
a key that fired and went nowhere are indistinguishable without them, and that
ambiguity is why three of the four hotkey faults on this desk survived as long
as they did -- so the script says how many shortcuts it registered, and says so
again on every activation.
*/
func Script(bindings map[string]string) string {
	var out strings.Builder
	out.WriteString("// Generated by hotaru. Edits here are overwritten on every install.\n")
	out.WriteString("var registered = 0;\n")

	for _, key := range sorted(bindings) {
		scene := bindings[key]
		fmt.Fprintf(&out, `
registerShortcut(%q, %q, %q, function() {
    print("hotaru: %s -> %s");
    callDBus(%q, %q, %q, "Apply", %q);
});
registered += 1;
`, shortcutName(key), fmt.Sprintf("hotaru: apply %s", scene), key,
			key, scene, BusName, string(ObjectPath), Interface, scene)
	}

	out.WriteString("\nprint(\"hotaru: registered \" + registered + \" shortcuts\");\n")
	return out.String()
}

/*
shortcutName is the identifier KDE stores the binding under.

Derived from the key rather than from the scene, and that is deliberate.
kglobalshortcutsrc entries outlive the script that made them, so an identifier
carrying the scene name would leave an orphan behind every time somebody
rebound a key -- which is exactly how eighteen `AIOScene*` entries came to be
sitting in that file holding sequences their program no longer uses.
*/
func shortcutName(key string) string {
	return "Hotaru" + unsafe.ReplaceAllString(key, "")
}

var unsafe = regexp.MustCompile(`[^A-Za-z0-9]`)

func sorted(bindings map[string]string) []string {
	out := make([]string, 0, len(bindings))
	for key := range bindings {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}
